### ISSUE TITLE
Voting: Balancer BIP-30

### ISSUE THREAD

**Issue by TheCryptoCommander** [Badger-Finance/badger-voting#1]
## Snapshot
https://snapshot.org/#/balancer.eth/proposal/0x3a2cd227ab45ce9773d8f83f876035afc3267f31b6a6de20ee8f58e7cbb7e978

## Option to vote for
Yes, let's do it

## Authorization
https://discord.com/channels/743271185751474307/1002561538105806900/1003120309903311010
![Balancer BIP-30](https://user-images.githubusercontent.com/110265830/182008482-b1a5ecc1-4555-454f-86b4-b74bf32562a4.jpg)

**Comment by SHAKOTN** [comment]
Done
![Screenshot 2022-07-31 at 10 32 10](https://user-images.githubusercontent.com/7059697/182015163-f3f5c9e9-06c0-4c1b-acad-940a7d441cad.png)
