### ISSUE TITLE
[VOTE] For the BADGER/rETH Pool 50/50 Gauge on Balancer

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-voting#10]
## Snapshot
https://snapshot.org/#/balancer.eth/proposal/0xd31432042f59ad18112c14747e4e8e1e428b0738d86dd9ed5fdb2329ef82b72d

## Option to vote for
Yes, let's do it

## Authorization
https://discord.com/channels/743271185751474307/842854176488161311/1032697248032768050

For some reason the emoji only shows 4 votes, but click into it and there are 7 votes in favor
![image](https://user-images.githubusercontent.com/113713830/197082449-755fa9a3-6074-4bd0-9512-4cd2cf11bcf0.png)

**Comment by SHAKOTN** [comment]
![Screenshot 2022-10-21 at 17 14 34](https://user-images.githubusercontent.com/7059697/197217034-d1a8017f-ac58-4ccd-aff8-c458ac27acbd.png)
 Done
