### ISSUE TITLE
[VOTE] Balancer BIP 91 - Temporarily Adjust Optimism Fee Split

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-voting#11]
## Snapshot
https://snapshot.org/#/balancer.eth/proposal/0x38bed268fe1536a6c8e9d5d5b3139bfba912b46507e2a72777cac691f58549d0

## Option to vote for
Yes, let's do it

## Authorization
(https://discord.com/channels/743271185751474307/842854176488161311/1033027082021785660)

![image](https://user-images.githubusercontent.com/113713830/197237941-15013f35-2f50-484f-a007-b154e6dc3cc9.png)

**Comment by SHAKOTN** [comment]
Voted Yes on https://snapshot.org/#/balancer.eth/proposal/0x38bed268fe1536a6c8e9d5d5b3139bfba912b46507e2a72777cac691f58549d0
