### ISSUE TITLE
[VOTE] Add XAI-FRAXBP to Gauge Controller

### ISSUE THREAD

**Issue by yoshuaus** [Badger-Finance/badger-voting#12]
## Snapshot
https://vote.convexfinance.com/#/proposal/0xe2637fd0a43f967dd5b2b833439908c46603f27af066bcec1ed89ccdad793807

## Option to vote for
<Yes>

## Authorization
Silo Finance plans to collaborate with BadgerDAO and this proposal enables their stable coin which will unlock many future features. We’ve asked the team to vote for us and were pointed in this direction, if there is anything you need we are more than willing to provide it. Please help us get our gauge live!

**Comment by yoshuaus** [comment]
Update! Sorry, I gave the link to the erroneous vote 227, The correct vote is 228 - sorry about that.

Vote Here: https://snapshot.org/#/cvx.eth/proposal/0x099c0df955199f0e6c28ecd0104397f389b242ece7f0ee7a5cb41ab0f13708c5

Let me know any questions/concerns, I am super willing to sit down and talk.

Telegram: @Tenzents
Discord: Tenzent#0038

**Comment by SHAKOTN** [comment]
Voting didn't happen. Closing this ticket
