### ISSUE TITLE
Aura snapshot [BIP 125] - Vote FOR

### ISSUE THREAD

**Issue by hasherror** [Badger-Finance/badger-voting#14]
## Snapshot
https://snapshot.org/#/aurafinance.eth/proposal/0xba0e84ad4240bd8f9737868763a46dd5588a35d9d856d4474b6e786bc8fde638

## Option to vote for
YES

## Authorization
https://discord.com/channels/743271185751474307/842854176488161311/1047941060145467412
![Screenshot_20221201-192547](https://user-images.githubusercontent.com/75948305/205276584-0caef6f4-f86e-452b-9302-339074d9f310.png)

**Comment by SHAKOTN** [comment]
![Screenshot 2022-12-02 at 17 24 31](https://user-images.githubusercontent.com/7059697/205326914-f7f685dc-1371-4f45-bc04-e81ab481f37c.png)
Done
