### ISSUE TITLE
[VOTE]: AURA 08 December 2022 - graviAURA Council Vote

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-voting#15]
## Snapshot
https://vote.aura.finance/#/proposal/0xee3d9361d2e32dfa569baaed775575691df8163fbcc8ab936afe4d433535ab15

## Option to vote for
BADGER/wBTC Council 10% graviAURA vote weight

## Authorization
![image](https://user-images.githubusercontent.com/113713830/206479984-ca178ee2-8d57-4e9c-a724-918ee54ef7e6.png)

**Comment by SHAKOTN** [comment]
@FreddytheFilosopher I believe bot is already voting for badger/wbtc with 10% fees?
![Screenshot 2022-12-09 at 11 07 37](https://user-images.githubusercontent.com/7059697/206665705-63a560a1-ba7e-4c8a-b03c-409d8272d9ae.png)

**Comment by FreddytheFilosopher** [comment]
Yes, indeed.
