### ISSUE TITLE
[VOTE] Aura AIP 19 - Recognizing and Approving AURA Distribution for Protocol Migration

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-voting#16]
## Snapshot
(https://vote.aura.finance/#/proposal/0x721bad941afce480a0998d9ac4eb5116295029d29987fb6b8f3bb2fe04270a7d)

## Option to vote for
"For"

## Authorization
https://discord.com/channels/743271185751474307/842854176488161311/1054786873274400819
![image](https://user-images.githubusercontent.com/113713830/208931961-56e9b2ea-1736-4ce3-a948-9ba5796a1465.png)
![image](https://user-images.githubusercontent.com/113713830/208932007-d8fe5327-7c21-4394-abb7-f872e5c8fe2a.png)

**Comment by SHAKOTN** [comment]
![Screenshot 2022-12-21 at 17 24 13](https://user-images.githubusercontent.com/7059697/208940806-67e50d20-9cd3-491d-b479-48931340995b.png)
Done
