### ISSUE TITLE
[VOTE] Aura Delegate Council Applications

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-voting#17]
## Snapshot
https://vote.aura.finance/#/proposal/0x711716fc66d411d4616b25c993ecea10c8cc9ff385ec86f02d7b85e8130b9dd7

## Option to vote for
TheCryptoCommander

## Authorization
https://discord.com/channels/743271185751474307/842854176488161311/1055500042523385977

![image](https://user-images.githubusercontent.com/113713830/209263919-ca3b7c3b-3f4e-4add-be20-a9653975184e.png)

**Comment by SHAKOTN** [comment]
![Screenshot 2022-12-23 at 11 20 54](https://user-images.githubusercontent.com/7059697/209308985-777273ef-60e6-4f72-8796-222e8034e0be.png)
Done
