### ISSUE TITLE
[VOTE] AURA [BIP-145] Fund the Balancer Maxis for Q1 2023

### ISSUE THREAD

**Issue by FreddytheFilosopher** [Badger-Finance/badger-voting#18]
## Snapshot
https://vote.aura.finance/#/proposal/0xa280743cf0e4ab5561d6dede89161522cc2b4828b80893faf402710a857211f4

## Option to vote for
Yes, let's do it

## Authorization
https://discord.com/channels/743271185751474307/842854176488161311/1060661867476959262

![image](https://user-images.githubusercontent.com/113713830/211034930-f28e0217-2356-4224-9f2a-635b3711ebc8.png)

**Comment by SHAKOTN** [comment]
![Screenshot 2023-01-06 at 16 58 27](https://user-images.githubusercontent.com/7059697/211037720-f607d54c-eab0-4a20-904c-895353fe6025.png)
