### ISSUE TITLE
[BIP-42] Enable rETH/weth Metastable Gauge [Optimism]

### ISSUE THREAD

**Issue by hasherror** [Badger-Finance/badger-voting#2]
## Snapshot
https://snapshot.org/#/balancer.eth/proposal/0x2ed11348cf46f833cf3f4dce484502a52407757f5e886e725fc50c03748bfccf

## Option to vote for
Yes

## Authorization
https://discord.com/channels/743271185751474307/842854176488161311/1008024475729661994

![Screenshot_20220814-073925](https://user-images.githubusercontent.com/75948305/184534983-01ab6c1c-07ba-4cee-bb11-8a1b50ed2ae5.png)

**Comment by SHAKOTN** [comment]
![Screenshot 2022-08-14 at 15 32 06](https://user-images.githubusercontent.com/7059697/184536974-4ec5bd9b-5fab-473b-968c-b00ab32f4693.png)

@hasherror voting is done. Consider closing ticket
