### ISSUE TITLE
[VOTE] Test voting on new veBAL system

### ISSUE THREAD

**Issue by Tritium-VLK** [Badger-Finance/badger-voting#3]
## Snapshot
https://snapshot.org/#/balancer.eth/proposal/0x07adfade8cf8fd0d033039dbe99228c0a5c172216b1c1646b8db9a87d0c7b832
## Option to vote for
Any option

## Authorization
This is a test vote to confirm that graviAURA can vote on veBAL proposals with the new system in place.  Please contract tritium and let him know the amount of veBAL voting.

**Comment by SHAKOTN** [comment]
![Screenshot 2022-08-23 at 15 06 59](https://user-images.githubusercontent.com/7059697/186153893-2e55467f-5174-4938-8259-038a49e8047d.png)
Voted with 121 veBAL
