### ISSUE TITLE
[VOTE] (CVX) Vote yes on Gauge Addition Proposal

### ISSUE THREAD

**Issue by spadaboom** [Badger-Finance/badger-voting#8]
## Snapshot
[https://snapshot.org/#/<voting.space.eth>/proposal/<proposal_id>](https://vote.convexfinance.com/#/proposal/bafkreidcr5hemvutigqzjihcaaeppepeumptbahywgbq5ezxxgvktqbyam)

## Option to vote for
YES
## Authorization
Treasury approved activity with $500k of treasury owned assets to be added to this pool once gauge approved. https://discord.com/channels/1011322803414388897/1011333638044008548/1022504264871989329

**Comment by SHAKOTN** [comment]
Related PR:
https://github.com/Badger-Finance/autovoter/pull/91

**Comment by SHAKOTN** [comment]
Voted on https://vote.convexfinance.com/#/proposal/bafkreidcr5hemvutigqzjihcaaeppepeumptbahywgbq5ezxxgvktqbyam YES
