### ISSUE TITLE
[BIP-78] Delegate Aave Holding to Llama

### ISSUE THREAD

**Issue by hasherror** [Badger-Finance/badger-voting#9]
## Snapshot
https://snapshot.org/#/balancer.eth/proposal/0xc77803ea0a567de8d43116720f66d00f5bd775427ed38e52aaa5f452f908fc02

## Option to vote for
Yes

## Authorization
https://discord.com/channels/743271185751474307/1025466347972468838/1025478936987172886

**Comment by SHAKOTN** [comment]
Voted YES on https://snapshot.org/#/balancer.eth/proposal/0xc77803ea0a567de8d43116720f66d00f5bd775427ed38e52aaa5f452f908fc02
![Screenshot 2022-10-01 at 20 35 56](https://user-images.githubusercontent.com/7059697/193421402-2addacc5-84e3-4b90-bd4e-319d12335af9.png)
